botId: BOT_1
port: 3004
description: MGC with EMA
instrument: F.US.MGC
accountId: '9627376'
strategy:
  type: EMA_RETRACE
  parameters:
    emaFast: 6
    emaSlow: 19
    mode: STANDARD
    maxBarsSinceEMA: 5
    postWinCandleTimeout: 60
    postLossCandleTimeout: 300
    minEMASpread: 0.5
    maxRiskPoints: 3
    stopLossBuffer: 1
    stopLossOffset: 0
    riskRewardRatio: 3
    trailingStopEnabled: false
    candleIntervalSeconds: 60
    emaUpdateMode: TICK_BASED
risk:
  dollarRiskPerTrade: 50
  maxConsecutiveLosses: 3
  maxDailyLoss: 800
  maxDailyProfit: 600
  maxOpenPositions: 1
  positionSizing:
    method: FIXED
    fixedSize: 1
exits:
  moveToBreakeven: false
  breakevenTrigger: 1.5
  partialExits: []
  trailingStop:
    enabled: false
    trigger: 1
    distance: 10
    adjustTP: true
tradingHours:
  enabled: false
  sessions:
    - name: Regular
      start: '09:30'
      end: '16:00'
      timezone: America/New_York
      days:
        - 1
        - 2
        - 3
        - 4
        - 5
execution:
  orderType: MARKET
  slippage:
    maxTicks: 10
  retryFailedOrders: true
  maxRetries: 1
monitoring:
  trackMetrics: false
  metricsInterval: 60000
  alertOnDrawdown: 500
  logTrades: false
  logLevel: ERROR
aggregator:
  enabled: true
  redisConfig:
    host: localhost
    port: 6379
  connectionManagerUrl: http://localhost:7500
  aggregatorUrl: http://localhost:7700
