botId: BOT_1
port: 3004
description: MGC Live Trading Test
instrument: F.US.MGC
accountId: '9627376'
testMode: false
marketDataSource: LIVE
strategy:
  type: TEST_TIME
  parameters:
    intervalMinutes: 5
    tradeDurationMinutes: 3
    candleLookbackMinutes: 1
    positionSize: 1
    maxRiskPoints: 3
    enableLogging: true
    dollarPerPoint: 10
    riskRewardRatio: 1
risk:
  dollarRiskPerTrade: 50
  maxConsecutiveLosses: 3
  maxDailyLoss: 800
  maxDailyProfit: 600
  maxOpenPositions: 1
  positionSizing:
    method: FIXED
    fixedSize: 1
exits:
  moveToBreakeven: false
  breakevenTrigger: 1.5
  partialExits: []
  trailingStop:
    enabled: false
    trigger: 1
    distance: 10
    adjustTP: true
tradingHours:
  enabled: false
  sessions:
    - name: Regular
      start: '09:30'
      end: '16:00'
      timezone: America/New_York
      days:
        - 1
        - 2
        - 3
        - 4
        - 5
execution:
  orderType: MARKET
  slippage:
    maxTicks: 10
  retryFailedOrders: true
  maxRetries: 1
monitoring:
  trackMetrics: true
  metricsInterval: 60000
  alertOnDrawdown: 500
  logTrades: true
  logLevel: INFO
aggregator:
  enabled: true
  redisConfig:
    host: localhost
    port: 6379
  connectionManagerUrl: http://localhost:7500
  aggregatorUrl: http://localhost:7700
